server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true

  dev:
    enabled: false

  dataStorage:
    enabled: true
    storageClass: "local-path"
    size: 5Gi

  service:
    enabled: true
    type: ClusterIP
    port: 8200

injector:
  enabled: true
  externalVaultAddr: "http://vault.vault.svc:8200"
